package maxeem.america.nasa.net

object ApodDTORaw {
    
    val mediaImage = """
            {"media_type":"image","date":"2019-12-10","url":"https://apod.nasa.gov/apod/image/1912/StarlinkTrails_Filter_1080.jpg","copyright":"Egon Filter","explanation":"What are those streaks over the horizon? New Starlink satellites reflecting sunlight. SpaceX launched 60 Starlink communication satellites in May and 60 more in November. These satellites and thousands more are planned by communications companies in the next few years that may make streaks like these relatively common. Concern has been voiced by many in the astronomical community about how reflections from these satellites may affect future observations into space.  In the pictured composite of 33 exposures, parallel streaks from Starlink satellites are visible over southern Brazil. Sunflowers dot the foreground, while a bright meteor was caught by chance on the upper right. Satellite reflections are not new -- the constellation of 66 first-generation Iridium satellites launched starting 20 years ago produced some flares so bright that they could be seen during the day. Most of these old Iridium satellites, however, have been de-orbited over the past few years.    Infinite Loop: Create an APOD Station in your classroom or Science Center.","hdurl":"https://apod.nasa.gov/apod/image/1912/StarlinkTrails_Filter_2048.jpg","service_version":"v1","title":"Starlink Satellite Trails over Brazil"}
        """.trimIndent()
    val mediaImageUppercase = """
            {"media_type":"IMAGE","date":"2019-12-10","url":"https://apod.nasa.gov/apod/image/1912/StarlinkTrails_Filter_1080.jpg","copyright":"Egon Filter","explanation":"What are those streaks over the horizon? New Starlink satellites reflecting sunlight. SpaceX launched 60 Starlink communication satellites in May and 60 more in November. These satellites and thousands more are planned by communications companies in the next few years that may make streaks like these relatively common. Concern has been voiced by many in the astronomical community about how reflections from these satellites may affect future observations into space.  In the pictured composite of 33 exposures, parallel streaks from Starlink satellites are visible over southern Brazil. Sunflowers dot the foreground, while a bright meteor was caught by chance on the upper right. Satellite reflections are not new -- the constellation of 66 first-generation Iridium satellites launched starting 20 years ago produced some flares so bright that they could be seen during the day. Most of these old Iridium satellites, however, have been de-orbited over the past few years.    Infinite Loop: Create an APOD Station in your classroom or Science Center.","hdurl":"https://apod.nasa.gov/apod/image/1912/StarlinkTrails_Filter_2048.jpg","service_version":"v1","title":"Starlink Satellite Trails over Brazil"}
        """.trimIndent()
    val mediaYouTube = """
            {"media_type":"video","date":"2019-12-02","url":"https://www.youtube.com/embed/ofZTOxC9JQ4?rel=0","explanation":"What's that black dot crossing the Sun? The planet Mercury. Mercury usually passes over or under the Sun, as seen from Earth, but last month the Solar System's innermost planet appeared to go just about straight across the middle.  Although witnessed by planet admirers across the globe, a particularly clear view was captured by the Solar Dynamics Observatory (SDO) in Earth orbit. The featured video was captured by the SDO's HMI instrument in a broad range of visible light, and compresses the 5 1/2 hour transit into about 13 seconds.  The background Sun was unusually quiet -- even for being near Solar Minimum -- and showed no sunspots. The next solar transit by Mercury will occur in 2032.","service_version":"v1","title":"Mercury Crosses a Quiet Sun"}
        """.trimIndent()
    val mediaYouTubeUppercase = """
            {"media_type":"Video","date":"2019-12-02","url":"https://www.YouTube.com/embed/ofZTOxC9JQ4?rel=0","explanation":"What's that black dot crossing the Sun? The planet Mercury. Mercury usually passes over or under the Sun, as seen from Earth, but last month the Solar System's innermost planet appeared to go just about straight across the middle.  Although witnessed by planet admirers across the globe, a particularly clear view was captured by the Solar Dynamics Observatory (SDO) in Earth orbit. The featured video was captured by the SDO's HMI instrument in a broad range of visible light, and compresses the 5 1/2 hour transit into about 13 seconds.  The background Sun was unusually quiet -- even for being near Solar Minimum -- and showed no sunspots. The next solar transit by Mercury will occur in 2032.","service_version":"v1","title":"Mercury Crosses a Quiet Sun"}
        """.trimIndent()
    val mediaUnknownGallery = """
            {"media_type":"gallery","date":"2002-02-02","url":"https://unsplash.com","explanation":"It's the Unsplash","service_version":"v1","title":"Unsplash home page"}
        """.trimIndent()
    val mediaUnknownVideo = """
            {"media_type":"video","date":"2001-01-01","url":"https://some-another-video.host/video/1","explanation":"Possible video 1 description","service_version":"v1","title":"Some vid"}
        """.trimIndent()
    
}
